<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" dir="ltr">
<head>
	<title>Aude's Tools | FedFlix</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link rel="stylesheet" type="text/css" href="http://toolserver.org/~aude/media/common/css/reset.css" />
	<link rel="stylesheet" type="text/css" href="http://toolserver.org/~aude/media/fedflix/css/main.css" />
	<script type="text/javascript" src="http://toolserver.org/~aude/media/common/js/jquery-1.5.2.min.js"></script>
	<script type="text/javascript" src="http://toolserver.org/~aude/media/fedflix/js/fedflix.js"></script>

</head>
<body>
<div id="header">
  <div class="inner">
    <h2><a href="http://toolserver.org/~aude/fedflix.fcgi/">FedFlix inventory</a></h2>
  </div>
  <div id="listselector">
      <span>Internet Archive</span>
  </div>

</div>
<div id="main">
  <div class="inner">
    <div id="toollist">
	<div id="articlecontainer">
	${content}
	<br clear="all" />
	</div>
    </div>
  </div>
</div>

<div id="footer">
  <div class="inner">
    <ul>
      <li><a href="http://toolserver.org/~aude/">Aude's Tools</a></li>
      <li><a href="http://en.wikipedia.org/wiki/User_talk:Aude">Contact</a></li>
    </ul>

  </div>
</div>
</body>
</html>

